name: "Bounty claimen: Check einreichen"
description: "Du hast vor Ort in Bitcoin bezahlt? Reiche deinen Check ein und verdiene Sats!"
title: "Check: [LOCATION-ID] – [DATUM]"
labels: ["pending", "check"]
body:
  - type: markdown
    attributes:
      value: |
        ## Satoshis für Berlin – Bounty claimen

        Du hast in Berlin vor Ort mit **Bitcoin** bezahlt? Super! Fülle dieses Formular aus und sichere dir deinen Bounty.

        ---

        ### Vor dem Einreichen

        1. Öffne die [Übersicht](https://satoshiinberlin.github.io/sats4berlin/) und klicke auf "Claim Bounty"
        2. Prüfe, ob der Bounty **verfügbar** ist (grüner Button)
        3. Klicke auf **"Claim Bounty"** – das Formular wird automatisch ausgefüllt

        > **Hinweis:** Orte im Cooldown (orangener Button) können erst nach Ablauf der Frist erneut geprüft werden.

        ---

  - type: input
    id: location_id
    attributes:
      label: "Location-ID"
      description: "Die ID findest du in der Übersicht (z.B. DE-BE-00042). Wenn du über 'Claim Bounty' kommst, ist sie bereits eingetragen."
      placeholder: "DE-BE-00042"
    validations:
      required: true

  - type: input
    id: date_time
    attributes:
      label: "Datum und Uhrzeit des Kaufs"
      description: "Wann hast du bezahlt? Ungefähre Uhrzeit reicht."
      placeholder: "25.01.2026, ca. 14:30"
    validations:
      required: true

  - type: dropdown
    id: check_type
    attributes:
      label: "Art des Checks"
      description: "Was trifft zu?"
      options:
        - "Normaler Check – Ort akzeptiert weiterhin Bitcoin"
        - "Kritische Änderung – Ort nimmt kein Bitcoin mehr / geschlossen / umgezogen"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### Nachweise hochladen

        Lade deine Nachweise bei einem Bilderhoster hoch und füge die Links unten ein:
        - [Catbox](https://catbox.moe/) – einfach, kein Account nötig
        - [Lutim](https://pic.infini.fr/) – Open Source
        - [Imgbb](https://imgbb.com/) – einfach, kein Account nötig

        **Wichtig:** Schwärze persönliche Daten (Name, Adresse, etc.) auf allen Bildern!

  - type: input
    id: public_post_url
    attributes:
      label: "1. Öffentlicher Post (Social Media)"
      description: 'Link zu deinem öffentlichen Post mit Foto/Video. Muss die Worte "Berlin" und "Bitcoin" enthalten.'
      placeholder: "https://x.com/deinname/status/..."
    validations:
      required: true

  - type: input
    id: receipt_proof_url
    attributes:
      label: "2. Kaufbeleg (Bon/Rechnung)"
      description: "Foto vom Kassenbon oder der Rechnung. Persönliche Daten schwärzen!"
      placeholder: "https://files.catbox.moe/..."
    validations:
      required: true

  - type: input
    id: payment_proof_url
    attributes:
      label: "3. Bitcoin-Zahlung"
      description: 'Screenshot der Wallet mit Bestätigung "bezahlt" – Betrag und Datum müssen sichtbar sein.'
      placeholder: "https://files.catbox.moe/..."
    validations:
      required: true

  - type: input
    id: venue_photo_url
    attributes:
      label: "4. Foto vom Ort"
      description: "Foto von Schild, Eingang oder Kasse – damit der Ort eindeutig erkennbar ist."
      placeholder: "https://files.catbox.moe/..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ### Zusätzliche Infos

  - type: textarea
    id: observations
    attributes:
      label: "Wie lief die Zahlung?"
      description: "Kurze Beschreibung: War es einfach? Gab es Probleme? Welche Wallet/App wurde genutzt?"
      placeholder: |
        Zahlung per Lightning an der Kasse, hat sofort funktioniert.
        "Bitcoin accepted" Aufkleber am Eingang sichtbar.
    validations:
      required: true

  - type: textarea
    id: suggested_updates
    attributes:
      label: "Änderungen am Eintrag nötig? (optional)"
      description: "Falls du Fehler in den Daten bemerkt hast (Öffnungszeiten, Adresse, Website, etc.)"
      placeholder: |
        Öffnungszeiten stimmen nicht: Laut Aushang Mo-Fr 10-19 Uhr (statt 10-18)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ### Auszahlung

        Nach erfolgreicher Prüfung (Label **approved**) erhältst du eine Nachricht mit Anweisungen zur Auszahlung.

        **Bitte poste deine Lightning-Adresse NICHT öffentlich in diesem Issue!**

        Die Auszahlung erfolgt anonym per Lightning oder eCash.

        ---

        **Danke für deinen Beitrag zu Satoshis für Berlin!**
